name: Build/release
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:win

      - name: Get version number
        id: get_version
        run: echo ::set-output name=version::v$(node -p "require('./package.json').version")

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tournament-overlay-remote-*.exe
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}