name: Build/release
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Get version number
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Output version number
        run: echo ${{ steps.get_version.outputs.version }}
